
package com.rahackya.ccassign.soapapp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://soapapp.ccassign.rahackya.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @return
     *     returns java.util.List<com.rahackya.ccassign.soapapp.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showAll", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.ShowAll")
    @ResponseWrapper(localName = "showAllResponse", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.ShowAllResponse")
    @Action(input = "http://soapapp.ccassign.rahackya.com/UserService/showAllRequest", output = "http://soapapp.ccassign.rahackya.com/UserService/showAllResponse")
    public List<User> showAll();

    /**
     * 
     * @param id
     * @return
     *     returns com.rahackya.ccassign.soapapp.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "show", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.Show")
    @ResponseWrapper(localName = "showResponse", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.ShowResponse")
    @Action(input = "http://soapapp.ccassign.rahackya.com/UserService/showRequest", output = "http://soapapp.ccassign.rahackya.com/UserService/showResponse")
    public User show(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "destroyUser", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.DestroyUser")
    @ResponseWrapper(localName = "destroyUserResponse", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.DestroyUserResponse")
    @Action(input = "http://soapapp.ccassign.rahackya.com/UserService/destroyUserRequest", output = "http://soapapp.ccassign.rahackya.com/UserService/destroyUserResponse")
    public boolean destroyUser(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.SayHelloResponse")
    @Action(input = "http://soapapp.ccassign.rahackya.com/UserService/sayHelloRequest", output = "http://soapapp.ccassign.rahackya.com/UserService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.AddUserResponse")
    @Action(input = "http://soapapp.ccassign.rahackya.com/UserService/addUserRequest", output = "http://soapapp.ccassign.rahackya.com/UserService/addUserResponse")
    public boolean addUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param id
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editUser", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.EditUser")
    @ResponseWrapper(localName = "editUserResponse", targetNamespace = "http://soapapp.ccassign.rahackya.com/", className = "com.rahackya.ccassign.soapapp.EditUserResponse")
    @Action(input = "http://soapapp.ccassign.rahackya.com/UserService/editUserRequest", output = "http://soapapp.ccassign.rahackya.com/UserService/editUserResponse")
    public boolean editUser(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "user", targetNamespace = "")
        User user);

}
